name: DevOps CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  terraform:
    name: Terraform checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Run terraform checks (fmt / init / validate if files exist)
        shell: bash
        run: |
          set -e
          TF_DIR=infrastructure/terraform
          if compgen -G "${TF_DIR}/*.tf" > /dev/null; then
            echo "Found Terraform files in ${TF_DIR}"
            terraform -chdir="${TF_DIR}" fmt -check -recursive
            terraform -chdir="${TF_DIR}" init -backend=false
            # validate may fail if providers aren't configured; keep output for debugging
            terraform -chdir="${TF_DIR}" validate || echo "terraform validate returned non-zero (check providers / config)"
          else
            echo "No Terraform files found in ${TF_DIR}, skipping Terraform checks"
          fi

  yamllint:
    name: YAML lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install yamllint
        run: python3 -m pip install --upgrade pip yamllint

      - name: Run yamllint on k8s/ansible if present
        shell: bash
        run: |
          set -e
          FOUND=false
          for d in infrastructure/kubernetes infrastructure/ansible; do
            if compgen -G "${d}/*.{yml,yaml}" > /dev/null; then
              echo "Linting YAML in $d"
              yamllint -s "$d" || exit 1
              FOUND=true
            fi
          done
          if [ "$FOUND" = false ]; then
            echo "No YAML files found in infrastructure/kubernetes or infrastructure/ansible, skipping yamllint"
          fi

  hadolint:
    name: Hadolint Dockerfile lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install hadolint
        run: |
          wget -q -O /usr/local/bin/hadolint \
            https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          chmod +x /usr/local/bin/hadolint

      - name: Lint Dockerfile if present
        shell: bash
        run: |
          set -e
          DOCKERFILE=infrastructure/docker/Dockerfile
          if [ -f "$DOCKERFILE" ]; then
            echo "Linting $DOCKERFILE"
            hadolint "$DOCKERFILE"
          else
            echo "No Dockerfile at $DOCKERFILE, skipping hadolint"
          fi
